# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=6)),
                ('status', models.IntegerField(choices=[(0, "open'"), (1, 'completed')])),
                ('due_date', models.DateField(default=None, null=True)),
                ('created_date', models.DateField(default=datetime.datetime(2016, 6, 23, 8, 17, 27, 653675))),
                ('modified_date', models.DateField(default=datetime.datetime(2016, 6, 23, 8, 17, 27, 653725), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, "open'"), (1, 'completed')])),
                ('created_date', models.DateField(default=datetime.datetime(2016, 6, 23, 8, 17, 27, 654382))),
                ('modified_date', models.DateField(default=datetime.datetime(2016, 6, 23, 8, 17, 27, 654407), null=True)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='parent_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoListApp.ToDoList'),
        ),
    ]
